"use client";
import { usePathname } from "next/navigation";

const route_entries: Array<{ pattern: RegExp; label: string }> = [
  // ─── Client routes ────────────────────────────────────────────────────────
  { pattern: /^\/$/, label: "Dashboard" },
  { pattern: /^\/deliverables$/, label: "Deliverables" },
  { pattern: /^\/resources\/[^/]+$/, label: "Resource Details" },
  { pattern: /^\/resources$/, label: "Resources" },
  { pattern: /^\/link-building\/orders\/[^/]+\/report$/, label: "Order Report" },
  { pattern: /^\/link-building\/orders\/[^/]+\/tracking$/, label: "Order Tracking" },
  { pattern: /^\/link-building\/orders\/[^/]+$/, label: "Order Details" },
  { pattern: /^\/link-building$/, label: "Link Building" },
  { pattern: /^\/premium-mentions$/, label: "Premium Mentions" },
  { pattern: /^\/new-content\/orders\/[^/]+\/intake$/, label: "New Content Intake" },
  { pattern: /^\/new-content$/, label: "New Content" },
  { pattern: /^\/content-refresh\/content-optimizations\/orders\/[^/]+\/intake$/, label: "Content Optimization Intake" },
  { pattern: /^\/content-refresh\/content-optimizations$/, label: "Content Optimizations" },
  { pattern: /^\/content-refresh\/content-briefs$/, label: "Content Briefs" },
  { pattern: /^\/sme-content\/internal-collaboration$/, label: "Internal SME Content Collaboration" },
  { pattern: /^\/sme-content\/authored-content$/, label: "SME Authored Content" },
  { pattern: /^\/sme-content\/enhanced-content$/, label: "SME Enhanced Content" },
  { pattern: /^\/seo-packages$/, label: "SEO Packages" },
  { pattern: /^\/profile$/, label: "Profile" },
  { pattern: /^\/orders\/[^/]+\/report$/, label: "Order Report" },
  { pattern: /^\/orders\/[^/]+\/tracking$/, label: "Order Tracking" },
  { pattern: /^\/orders\/session\/[^/]+$/, label: "Order Session" },
  { pattern: /^\/orders\/[^/]+$/, label: "Order Details" },
  { pattern: /^\/orders$/, label: "Orders" },
  { pattern: /^\/billing$/, label: "Billing" },
  { pattern: /^\/invoices\/[^/]+$/, label: "Invoice Details" },
  { pattern: /^\/invoices$/, label: "Invoices" },
  { pattern: /^\/credits\/buy$/, label: "Buy Credits" },
  { pattern: /^\/credits\/purchases$/, label: "Credit Purchases" },
  { pattern: /^\/credits$/, label: "Credits" },
  { pattern: /^\/support\/new$/, label: "New Support Ticket" },
  { pattern: /^\/support\/[^/]+$/, label: "Support Ticket" },
  { pattern: /^\/support$/, label: "Support" },
  { pattern: /^\/schedule-a-call$/, label: "Schedule a Call" },
  { pattern: /^\/notifications$/, label: "Notifications" },
  { pattern: /^\/news\/[^/]+$/, label: "News Article" },
  { pattern: /^\/news$/, label: "News" },
  { pattern: /^\/store$/, label: "Store" },
  { pattern: /^\/tools$/, label: "Tools" },
  { pattern: /^\/team$/, label: "Team" },
  { pattern: /^\/keeping-track$/, label: "Keeping Track" },

  // ─── Admin routes ─────────────────────────────────────────────────────────
  { pattern: /^\/admin\/dashboard$/, label: "Dashboard" },
  { pattern: /^\/admin\/users\/[^/]+$/, label: "User Details" },
  { pattern: /^\/admin\/users$/, label: "Users" },
  { pattern: /^\/admin\/clients\/invitations$/, label: "Client Invitations" },
  { pattern: /^\/admin\/clients$/, label: "All Clients" },
  { pattern: /^\/admin\/organizations\/[^/]+$/, label: "Organization Details" },
  { pattern: /^\/admin\/organizations$/, label: "Organizations" },
  { pattern: /^\/admin\/orders\/[^/]+\/report$/, label: "Order Report" },
  { pattern: /^\/admin\/orders\/[^/]+\/tracking$/, label: "Order Tracking" },
  { pattern: /^\/admin\/orders\/session\/[^/]+$/, label: "Order Session" },
  { pattern: /^\/admin\/orders\/[^/]+$/, label: "Order Details" },
  { pattern: /^\/admin\/orders$/, label: "Orders" },
  { pattern: /^\/admin\/tracking$/, label: "Tracking" },
  { pattern: /^\/admin\/scheduled-calls\/[^/]+$/, label: "Appointment Details" },
  { pattern: /^\/admin\/scheduled-calls$/, label: "Scheduled Calls" },
  { pattern: /^\/admin\/invoices\/create$/, label: "Create Invoice" },
  { pattern: /^\/admin\/invoices\/[^/]+\/edit$/, label: "Edit Invoice" },
  { pattern: /^\/admin\/invoices\/[^/]+$/, label: "Invoice Details" },
  { pattern: /^\/admin\/invoices$/, label: "Invoices" },
  { pattern: /^\/admin\/credits\/clients$/, label: "Clients Credits" },
  { pattern: /^\/admin\/credits\/purchases$/, label: "Credit Purchases" },
  { pattern: /^\/admin\/credits$/, label: "Assign Credits" },
  { pattern: /^\/admin\/link-building$/, label: "Link Building" },
  { pattern: /^\/admin\/premium-mentions\/appointments\/[^/]+$/, label: "Appointment Details" },
  { pattern: /^\/admin\/premium-mentions\/appointments$/, label: "Premium Mentions Appointments" },
  { pattern: /^\/admin\/premium-mentions$/, label: "Premium Mentions" },
  { pattern: /^\/admin\/sme-content\/authored\/[^/]+\/edit$/, label: "Edit Authored Content" },
  { pattern: /^\/admin\/sme-content\/authored\/new$/, label: "New Authored Content" },
  { pattern: /^\/admin\/sme-content\/authored$/, label: "Authored Content" },
  { pattern: /^\/admin\/sme-content\/collaboration\/[^/]+\/edit$/, label: "Edit Collaboration" },
  { pattern: /^\/admin\/sme-content\/collaboration\/new$/, label: "New Collaboration" },
  { pattern: /^\/admin\/sme-content\/collaboration$/, label: "SME Collaboration" },
  { pattern: /^\/admin\/sme-content\/enhanced\/[^/]+\/edit$/, label: "Edit Enhanced Content" },
  { pattern: /^\/admin\/sme-content\/enhanced\/new$/, label: "New Enhanced Content" },
  { pattern: /^\/admin\/sme-content\/enhanced$/, label: "Enhanced Content" },
  { pattern: /^\/admin\/sme-content$/, label: "SME Content" },
  { pattern: /^\/admin\/sme-appointments\/[^/]+$/, label: "SME Appointment Details" },
  { pattern: /^\/admin\/sme-appointments$/, label: "SME Appointments" },
  { pattern: /^\/admin\/new-content\/orders\/[^/]+\/intake$/, label: "Order Intake" },
  { pattern: /^\/admin\/new-content\/orders\/[^/]+$/, label: "Order Details" },
  { pattern: /^\/admin\/new-content\/orders$/, label: "New Content Orders" },
  { pattern: /^\/admin\/new-content$/, label: "New Content" },
  { pattern: /^\/admin\/content-optimization\/orders\/[^/]+\/intake$/, label: "Order Intake" },
  { pattern: /^\/admin\/content-optimization\/orders\/[^/]+$/, label: "Order Details" },
  { pattern: /^\/admin\/content-optimization\/orders$/, label: "Content Optimization Orders" },
  { pattern: /^\/admin\/content-optimization$/, label: "Content Optimization" },
  { pattern: /^\/admin\/content-briefs\/orders\/[^/]+\/intake$/, label: "Content Brief Intake" },
  { pattern: /^\/admin\/content-briefs$/, label: "Content Briefs" },
  { pattern: /^\/admin\/content-refresh\/orders\/[^/]+$/, label: "Order Details" },
  { pattern: /^\/admin\/content-refresh\/orders$/, label: "Content Refresh Orders" },
  { pattern: /^\/admin\/content-refresh$/, label: "Content Refresh" },
  { pattern: /^\/admin\/seo-packages-subscriptions$/, label: "SEO Packages Subscriptions" },
  { pattern: /^\/admin\/seo-packages-appointments\/[^/]+$/, label: "Appointment Details" },
  { pattern: /^\/admin\/seo-packages-appointments$/, label: "SEO Packages Appointments" },
  { pattern: /^\/admin\/seo-packages$/, label: "SEO Packages" },
  { pattern: /^\/admin\/coupons\/new$/, label: "New Coupon" },
  { pattern: /^\/admin\/coupons\/[^/]+\/edit$/, label: "Edit Coupon" },
  { pattern: /^\/admin\/coupons$/, label: "Coupons" },
  { pattern: /^\/admin\/discounts\/new$/, label: "New Discount" },
  { pattern: /^\/admin\/discounts\/[^/]+\/edit$/, label: "Edit Discount" },
  { pattern: /^\/admin\/discounts$/, label: "Discounts" },
  { pattern: /^\/admin\/news\/new$/, label: "New News" },
  { pattern: /^\/admin\/news\/[^/]+\/edit$/, label: "Edit News" },
  { pattern: /^\/admin\/news$/, label: "News & Promos" },
  { pattern: /^\/admin\/news-placements$/, label: "News Placements" },
  { pattern: /^\/admin\/resources\/new$/, label: "New Resource" },
  { pattern: /^\/admin\/resources\/[^/]+\/edit$/, label: "Edit Resource" },
  { pattern: /^\/admin\/resources$/, label: "Resources" },
  { pattern: /^\/admin\/support-tickets\/[^/]+$/, label: "Support Ticket Details" },
  { pattern: /^\/admin\/support-tickets$/, label: "Support Tickets" },
  { pattern: /^\/admin\/teams\/new$/, label: "New Team" },
  { pattern: /^\/admin\/teams\/[^/]+\/edit$/, label: "Edit Team" },
  { pattern: /^\/admin\/teams\/[^/]+$/, label: "Team Details" },
  { pattern: /^\/admin\/teams$/, label: "Teams" },
  { pattern: /^\/admin\/invitations$/, label: "Invitations" },
  { pattern: /^\/admin\/notifications$/, label: "Notifications" },
  { pattern: /^\/admin\/profile$/, label: "Profile" },
  { pattern: /^\/admin\/email-notifications$/, label: "Email Settings" },
  { pattern: /^\/admin\/roles$/, label: "Roles" },
  { pattern: /^\/admin\/websocket$/, label: "WebSocket" },
];

export function useBreadcrumb(): string {
  const pathname = usePathname();

  for (const entry of route_entries) {
    if (entry.pattern.test(pathname)) {
      return entry.label;
    }
  }

  const segments = pathname.split("/").filter(Boolean);
  if (segments.length === 0) return "Dashboard";

  const last = segments[segments.length - 1];
  return last
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
